name: Runecraft
version: Scala Alpha
authors: [ Zeerix, SuperLlama, C'tri, RivkiinShadows, josiah42, Amuxix, lvletei ]
main: me.amuxix.Runecraft
website: http://forums.bukkit.org/threads/Runecraft.14897/